name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Npm install DexieWrapper.Test
      run: npm install 
      working-directory: DexieWrapper.Test
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release
      working-directory: DexieWrapper
    - name: Push
      run: dotnet nuget push "DexieWrapper/bin/Release/Nosthy.Blazor.DexieWrapper.0.1.0.nupkg" --api-key oy2cr7n4uahdzhr6f7eqwennhhc4i5dupeqnlsegesebc4 --source "github"
